### ISSUE TITLE
Spatially varying index structure, GDS or geometry import

### ISSUE THREAD

**Issue by CecilPham** [BYUCamachoLab/emepy#2]
Hi,

I would like to know if there was any possibility of using a custom epsilon function for the definition of the 2D waveguide index (for a graded index for example). EMpy allows custom eps functions but I'm not sure how to proceed with this package.

I would also like to know if there was any support for GDS files for importing waveguide geometry, or if it was possible to define geometry externally (by providing a list of vertices for a polygon for example). I'd like to experiment simulating directional couplers if it is possible.

Thanks,
Best regards.

**Comment by hammy4815** [comment]
Hello, It is possible to define custom epsilon functions using the EMpy wrapper capabilities of EMEPy. However, our neural networks are only trained for waveguide-based geometries. If you are interested in utilizing EMpy's wrapper in EMEPy to perform EMEPy, you should create a class that inherits from ModeSolver found in emepy.fd. 

class ModeSolver(object):
    def __init__(self, **kwargs):
        """ModeSolver class constructor
        """
        raise NotImplementedError
    def solve(self):
        """Solves the eigenmode solver for the specific eigenmodes of desire
        """
        raise NotImplementedError
    def clear(self):
        """Clears the modesolver's eigenmodes to make memory
        """
        raise NotImplementedError
    def get_mode(self, mode_num):
        """Must extract the mode of choice
            Parameters
            ----------
            mode_num : int 
                index of the mode of choice
        """
        raise NotImplementedError
        
If you need more help with this let me know. 

As for the GDS file compatibility, there is not an explicit GDS module in EMEPy as of yet. However, you can use a python module such as gdspy to read the file, and create a list of objects. You can then create EMEPy objects from those individually using a loop for example, however each 2d cross section must be defined for your device. Thus, this is very dependent on what your devices look like and might look different based on your geometries. Let me know if you have any more questions regarding this topic.

**Comment by hammy4815** [comment]
https://github.com/BYUCamachoLab/emepy/blob/master/examples/structures/directional_coupler.ipynb

This example creates a directional coupler using a custom epsilon. I'm going to close this issue but feel free to let me know if you have further questions regarding this topics.
