### ISSUE TITLE
Installation of the neural network models

### ISSUE THREAD

**Issue by jkrimmer** [BYUCamachoLab/emepy#30]
Unfortunately, the installation instructions for the neural network models do not exist anymore. The link provided in the docs leads to a non-existing page: [Link](https://github.com/BYUCamachoLab/emepy/blob/main/emepy/models/README.md). 

Is there any way to access these models to run the example geometry_notebooks/waveguide.ipynb?

Thanks a lot!

**Comment by hammy4815** [comment]
Hi @jkrimmer,

It appears you're right and I forgot to include the link to the models when I reformatted the repo. The models are large so I removed them from all commits to keep the repo light-weight. The models can be found here - 

https://byu.box.com/s/xtpp2h8vfwp4l07wdl5559j3vnip5cqj

They should be download and placed in:

~/.../emepy/emepy/models/Hy_chunks
~/.../emepy/emepy/models/Hx_chunks
~/.../emepy/emepy/models/neff_pickle

**Comment by jkrimmer** [comment]
Hi @hammy4815 ,

Thank you for taking care of this issue this quickly! I will download the models and try to run the examples tomorrow. In case anything is not working out, I will reopen this issue.

Cheers
Jonas
